id: P8FBAB3CC
initial_creation_type: input
source_metadata:
  title: Fourth Dodrupchen Rinpoche Series
  language: de
  description: 'Texts by and about the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
    (thub bstan phrin las dpal bzang po, 1927–2022) alias Jigme Trinlé Palbar (''jigs
    med phrin las dpal ''bar):'
  volume:
    0a1e542c50f143309103cf1d31d15d79:
      title: Aspiration for All Lives to Come
      parent: Aspiration Prayers
    5abe323db9384e0da7368fe5a928cfae:
      title: Guru Yoga
      parent: Guru Yoga
    5c3749660e3347d783b4caf4a7d1b85c:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    180530ccc1834f0fbe6e0c34057e6b5c:
      title: Prayer to the Guru
      parent: Prayers
    c39ce4caee284cdeb5c7f790cb2eb6bf:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
    f1780b31c9e04faa9d4bf989b4ac804b:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
    2d3aa2121b3a48a7b6886a132cbc2da1:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Swift Rebirth Prayers
    503686be36cd44e085fdd41caaee8ca1:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
    8462a3e89a3c46e18bfdd94eab3d526c:
      title: 'The Lotus Garland: A Short Feast-Offering for the Female Practice of
        the Heart Essence of the Vast Expanse'
      parent: Tsok
created_at: '2022-02-28T23:19:49.078470'
last_modified_at: '2022-02-28T23:19:49.078473'
